<?php

// This file has been auto-generated by the Symfony Routing Component.

return array(
    array(
        array(
            null,
            array(
                null,
                array(array('path', '/just_head'), null, array('HEAD' => 'HEAD'), null, array('_route' => 'just_head')),
                array(array('path', '/head_and_get'), null, array('HEAD' => 'HEAD', 'GET' => 'GET'), null, array('_route' => 'head_and_get')),
                array(array('path', '/get_and_head'), null, array('GET' => 'GET', 'HEAD' => 'HEAD'), null, array('_route' => 'get_and_head')),
                array(array('path', '/post_and_get'), null, array('POST' => 'POST', 'HEAD' => 'HEAD'), null, array('_route' => 'post_and_head')),
                array(
                    '/put_and_post',
                    array(array('path', '/put_and_post'), null, array('PUT' => 'PUT', 'POST' => 'POST'), null, array('_route' => 'put_and_post')),
                    array(array('path', '/put_and_post'), null, array('PUT' => 'PUT', 'GET' => 'GET', 'HEAD' => 'HEAD'), null, array('_route' => 'put_and_get_and_head')),
                ),
            ),
        ),
    ),
    array(),
);
