<?php

// This file has been auto-generated by the Symfony Routing Component.

return array(
    array(
        array(
            null,
            array(
                null,
                array(
                    '/rootprefix',
                    array(array('path', '/rootprefix/test'), null, null, null, array('_route' => 'static')),
                    array(array('match', '#^/rootprefix/(?P<var>[^/]++)$#s'), null, null, null, array('_route' => 'dynamic')),
                ),
                array(array('path', '/with-condition'), 0, null, null, array('_route' => 'with-condition')),
            ),
        ),
    ),
    array(
        function ($context, $request) { return ($context->getMethod() == "GET"); },
    ),
);
