<?php

return Symfony\CS\Config\Config::create()
    ->setUsingLinter(false)
    ->setUsingCache(true)
    ->fixers(array(
        'long_array_syntax',
        'php_unit_construct',
        'php_unit_dedicate_assert',
    ))
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->in(__DIR__)
            ->exclude(array(
                // directories containing files with content that is autogenerated by `var_export`, which breaks CS in output code
                'src/Symfony/Component/DependencyInjection/Tests/Fixtures',
                'src/Symfony/Component/Routing/Tests/Fixtures/dumper',
                // fixture templates
                'src/Symfony/Component/Templating/Tests/Fixtures/templates',
                'src/Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/Resources/Custom',
                // generated fixtures
                'src/Symfony/Component/VarDumper/Tests/Fixtures',
                // resource templates
                'src/Symfony/Bundle/FrameworkBundle/Resources/views/Form',
            ))
            // file content autogenerated by `var_export`
            ->notPath('src/Symfony/Component/Translation/Tests/fixtures/resources.php')
            // autogenerated xmls
            ->notPath('src/Symfony/Component/Console/Tests/Fixtures/application_1.xml')
            ->notPath('src/Symfony/Component/Console/Tests/Fixtures/application_2.xml')
            // yml
            ->notPath('src/Symfony/Component/Yaml/Tests/Fixtures/sfTests.yml')
            // test template
            ->notPath('src/Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/Resources/Custom/_name_entry_label.html.php')
            // explicit heredoc test
            ->notPath('src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php')
    )
;
