<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUWVxv1z\Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUWVxv1z/Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUWVxv1z.legacy');

    return;
}

if (!\class_exists(Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUWVxv1z\Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer::class, Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer::class, false);
}

return new \ContainerUWVxv1z\Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer([
    'container.build_hash' => 'UWVxv1z',
    'container.build_id' => '47a5fe58',
    'container.build_time' => 1696976086,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUWVxv1z');
