<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\KeyManagement\Command;

use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\KeyManagement\DecrypterInterface;
use Symfony\Component\KeyManagement\EncrypterInterface;
use Symfony\Component\KeyManagement\EnvelopeEncrypter;
use Symfony\Contracts\Service\ServiceProviderInterface;

/**
 * @author Florent Morselli <florent.morselli@spomky-labs.com>
 *
 * @experimental
 */
#[AsCommand(
    name: 'key-management:encrypt',
    description: 'Encrypt a value with a configured KMS key',
    help: <<<'HELP'
        The <info>%command.name%</info> command produces an envelope-encrypted blob suitable for
        arbitrary-size payloads: a fresh data key is generated by the KMS, the
        plaintext is encrypted locally with AES-256-GCM, and the (key id, wrapped
        data key, IV, tag, ciphertext) are bundled into a self-contained binary
        envelope. The result is emitted as base64.

          <info>php %command.full_name% app-key 'hello world'</info>
          <info>cat secrets.json | php %command.full_name% app-key</info>

        The key id is embedded in the envelope, so <info>key-management:decrypt</info> only needs the blob.

        Both commands read STDIN when their payload argument is omitted and write their
        diagnostics to STDERR, so <info>key-management:decrypt</info> pipes into this one to re-encrypt
        an envelope under another key, for instance after a key rotation.

        When several KMS clients are registered, pick one with <comment>--client</comment>:

          <info>php %command.full_name% --client=aws app-key 'hello world'</info>

        <comment>--aad</comment> binds additional authenticated data to the ciphertext. The same
        exact bytes must be supplied to <info>key-management:decrypt</info>.

          <info>php %command.full_name% app-key 'hello' --aad 'tenant=acme;env=prod'</info>
        HELP,
)]
final class EncryptCommand
{
    use CommandTrait;

    /**
     * @param ServiceProviderInterface<EncrypterInterface&DecrypterInterface>|null $clients
     */
    public function __construct(
        private readonly ?ServiceProviderInterface $clients = null,
    ) {
    }

    public function __invoke(
        InputInterface $input,
        OutputInterface $output,
        SymfonyStyle $io,
        #[Argument(name: 'key-id', description: 'KMS key identifier (backend-specific: alias, ARN, key URL, ...)')]
        string $keyId,
        #[Argument(description: 'Plaintext to encrypt; read from STDIN if omitted')]
        #[\SensitiveParameter]
        ?string $value = null,
        #[Option(description: 'Name of the KMS client to use (omit when only one is registered)', suggestedValues: [self::class, 'suggestClients'])]
        ?string $client = null,
        #[Option(description: 'Additional Authenticated Data, treated as opaque bytes; the exact same value must be supplied to key-management:decrypt')]
        ?string $aad = null,
    ): int {
        $errorIo = $io->getErrorStyle();

        $encrypter = self::resolveEnvelopeEncrypter($this->clients, $client, $errorIo);
        if (!$encrypter instanceof EnvelopeEncrypter) {
            return $encrypter;
        }

        if (null === $value) {
            if (null === $stream = self::resolvePayloadStream($input)) {
                $errorIo->error('No plaintext to encrypt: pass it as an argument or pipe it to STDIN.');

                return Command::INVALID;
            }

            $value = stream_get_contents($stream);
            if (false === $value) {
                $errorIo->error('Failed to read plaintext from STDIN.');

                return Command::FAILURE;
            }
        }

        $envelope = $encrypter->encrypt($keyId, $value, $aad ?? '');

        $output->writeln(base64_encode((string) $envelope), OutputInterface::OUTPUT_RAW);

        return Command::SUCCESS;
    }
}
