<?php

namespace ContainerUWVxv1z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_AssetMapper_Command_Debug_LazyService extends Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer
{
    /**
     * Gets the private '.asset_mapper.command.debug.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.asset_mapper.command.debug.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('debug:asset-map', [], 'Output all mapped assets', false, #[\Closure(name: 'asset_mapper.command.debug', class: 'Symfony\\Component\\AssetMapper\\Command\\DebugAssetMapperCommand')] fn (): \Symfony\Component\AssetMapper\Command\DebugAssetMapperCommand => ($container->privates['asset_mapper.command.debug'] ?? $container->load('getAssetMapper_Command_DebugService')));
    }
}
