<?php

namespace ContainerUWVxv1z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Compiler_SourceMappingUrlsCompilerService extends Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer
{
    /**
     * Gets the private 'asset_mapper.compiler.source_mapping_urls_compiler' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Compiler\SourceMappingUrlsCompiler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Compiler/AssetCompilerInterface.php';
        include_once \dirname(__DIR__, 6).'/Compiler/AssetCompilerPathResolverTrait.php';
        include_once \dirname(__DIR__, 6).'/Compiler/SourceMappingUrlsCompiler.php';

        return $container->privates['asset_mapper.compiler.source_mapping_urls_compiler'] = new \Symfony\Component\AssetMapper\Compiler\SourceMappingUrlsCompiler();
    }
}
