<?php

namespace ContainerUWVxv1z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_AssetPackageService extends Symfony_Component_AssetMapper_Tests_fixtures_AssetMapperTestAppKernelTestDebugContainer
{
    /**
     * Gets the private 'asset_mapper.asset_package' shared service.
     *
     * @return \Symfony\Component\AssetMapper\MapperAwareAssetPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/MapperAwareAssetPackage.php';

        return $container->privates['asset_mapper.asset_package'] = new \Symfony\Component\AssetMapper\MapperAwareAssetPackage(($container->privates['asset_mapper.asset_package.inner'] ?? $container->load('getAssetMapper_AssetPackage_InnerService')), ($container->privates['asset_mapper'] ?? self::getAssetMapperService($container)));
    }
}
