#!/usr/bin/env bash

# This file is part of the Symfony package.
#
# (c) Fabien Potencier <fabien@symfony.com>
#
# For the full copyright and license information, please view
# https://symfony.com/doc/current/contributing/code/license.html

# Tests the shell completion scripts against real shells.
#
# Usage: run.sh [bash|zsh|fish|all]

set -u

dir="$(cd "$(dirname "$0")" && pwd)"
shells="${1:-all}"
[ "$shells" = "all" ] && shells="bash zsh fish"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# make the fixture application available as "app" in the PATH
mkdir -p "$tmp/bin"
ln -s "$dir/app" "$tmp/bin/app"
chmod +x "$dir/app"
export PATH="$tmp/bin:$PATH"

passed=0
failed=0
skipped=0

fail() {
    failed=$((failed + 1))
    echo "KO $1"
    [ -n "${GITHUB_ACTIONS:-}" ] && echo "::error::$1"
    shift
    printf '%s\n' "$@" | sed 's/^/    /'
}

pass() {
    passed=$((passed + 1))
    echo "OK $1"
}

normalize() {
    grep -v '^$' | LC_ALL=C sort -u
}

dump_script() {
    local shell="$1" script="$tmp/completion.$shell"

    if ! app completion "$shell" > "$script" 2> "$tmp/dump.err"; then
        fail "[$shell] dump the completion script" "$(cat "$tmp/dump.err")"
        return 1
    fi

    if grep -q '{{' "$script"; then
        fail "[$shell] all placeholders are replaced" "$(grep -n '{{' "$script")"
        return 1
    fi

    if ! grep -q '_sf_app' "$script"; then
        fail "[$shell] the command name is used in the script"
        return 1
    fi

    pass "[$shell] dump the completion script"
}

# Runs one case and compares the suggestions with the expectations
run_case() {
    local shell="$1" command_line="$2" expected="$3" name="[$shell] $2"
    local driver actual

    case "$shell" in
        bash) driver=(bash "$dir/drivers/bash.sh") ;;
        zsh) driver=(zsh "$dir/drivers/zsh.zsh") ;;
        fish) driver=(fish "$dir/drivers/fish.fish") ;;
    esac

    actual="$("${driver[@]}" "$tmp/completion.$shell" "$command_line" 2> "$tmp/case.err" | normalize)"
    expected="$(printf '%s' "$expected" | tr ';' '\n' | normalize)"

    if [ "$actual" = "$expected" ]; then
        pass "$name"

        return 0
    fi

    fail "$name" "expected:" "$expected" "actual:" "${actual:-<none>}" "$(cat "$tmp/case.err")"
}

# The completion must not run when the script was generated by another version of
# the API. Only bash reports the error, zsh and fish discard the error output.
test_api_version() {
    local script="$tmp/completion-outdated.bash" output

    sed 's/-a1/-a0.9/' "$tmp/completion.bash" > "$script"
    output="$(bash "$dir/drivers/bash.sh" "$script" 'app demo:' 2>&1)"

    case "$output" in
        *'Completion script version is not supported'*) pass "[bash] outdated completion script is detected" ;;
        *) fail "[bash] outdated completion script is detected" "$output" ;;
    esac
}

# bash-completion is not installed everywhere, for instance on macOS: the script
# must explain it instead of sending an incomplete request to the application
test_missing_bash_completion() {
    local output

    output="$(bash --noprofile --norc -c '
        source "$1"
        COMP_WORDS=(app demo:) COMP_CWORD=1 COMP_LINE="app demo:" COMP_POINT=9 COMPREPLY=()
        _sf_app
        printf "suggestions=%s\n" "${#COMPREPLY[@]}"
    ' _ "$tmp/completion.bash" 2>&1)"

    case "$output" in
        *'requires the "bash-completion" package'*'suggestions=0'*) pass "[bash] missing bash-completion is reported" ;;
        *) fail "[bash] missing bash-completion is reported" "$output" ;;
    esac
}

# The command may be reached through an alias, which can carry arguments. The
# driver cannot be used here, aliases need a shell of their own.
test_alias() {
    local name="$1" definition="$2" expected="$3" actual

    actual="$(bash --noprofile --norc -c '
        shopt -s expand_aliases
        source "$1/drivers/bash-completion.sh"
        source "$2"
        alias "$3"
        compopt() { :; }
        COMP_WORDS=("${3%%=*}" demo : "") COMP_CWORD=3 COMP_LINE="${3%%=*} demo:" COMP_POINT=9 COMPREPLY=()
        _sf_app
        printf "%s\n" "${COMPREPLY[@]}"
    ' _ "$dir" "$tmp/completion.bash" "$definition" 2> "$tmp/case.err" | normalize)"

    expected="$(printf '%s' "$expected" | tr ';' '\n' | normalize)"

    if [ "$actual" = "$expected" ]; then
        pass "[bash] completion through $name"
    else
        fail "[bash] completion through $name" "expected:" "$expected" "actual:" "${actual:-<none>}" "$(cat "$tmp/case.err")"
    fi
}

for shell in $shells; do
    if ! command -v "$shell" > /dev/null; then
        skipped=$((skipped + 1))
        echo "SKIP [$shell] $shell is not installed"

        continue
    fi

    echo "--- $shell ($("$shell" --version | head -n1))"

    dump_script "$shell" || continue

    while IFS='|' read -r case_shells command_line expected; do
        case "$case_shells" in
            ''|'#'*) continue ;;
        esac

        if [ "$case_shells" != "all" ] && [[ ",$case_shells," != *",$shell,"* ]]; then
            continue
        fi

        run_case "$shell" "${command_line//%app%/$dir/app}" "$expected"
    done < "$dir/cases.txt"

    if [ "$shell" = "bash" ]; then
        test_api_version
        test_missing_bash_completion
        test_alias 'an alias' 'sfa=app' 'hello;other;special'
        test_alias 'an alias with arguments' "sfb=app --no-ansi" 'hello;other;special'
    fi
done

echo
echo "$passed passed, $failed failed, $skipped skipped"

[ "$failed" -eq 0 ]
