<?php

namespace ContainerWeYQspU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpMessageFactoryInterfaceService extends Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface' shared autowired service.
     *
     * @return \Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['nyholm.psr_factory'] ??= new \Nyholm\Psr7\Factory\Psr17Factory());

        return $container->privates['Symfony\\Bridge\\PsrHttpMessage\\HttpMessageFactoryInterface'] = new \Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory($a, $a, $a, $a);
    }
}
