<?php

namespace ContainerWeYQspU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpFoundationFactoryInterfaceService extends Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface' shared autowired service.
     *
     * @return \Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Symfony\\Bridge\\PsrHttpMessage\\HttpFoundationFactoryInterface'] = new \Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory();
    }
}
