<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Messenger\Bridge\AmpSql\Transport\Backend;

use Amp\Sql\SqlConnection;
use Amp\Sql\SqlTransaction;
use Symfony\Component\Messenger\Exception\TransportException;

/** @internal */
final class PostgresBackend implements BackendInterface
{
    public function getNowExpression(): string
    {
        return 'CAST(EXTRACT(EPOCH FROM clock_timestamp()) * 1000 AS BIGINT)';
    }

    public function getClaimLockSql(): string
    {
        return ' FOR UPDATE SKIP LOCKED';
    }

    public function validateVersion(SqlConnection $connection): void
    {
        $version = $connection->query("SELECT current_setting('server_version_num') AS version")->fetchRow()['version'] ?? null;
        if (!\is_int($version) && (!\is_string($version) || !ctype_digit($version))) {
            throw new TransportException('Could not determine the PostgreSQL server version.');
        }
        if (100000 > (int) $version) {
            throw new TransportException('AMPHP SQL requires PostgreSQL 10 or newer.');
        }
    }

    public function setup(SqlConnection $connection, string $table): void
    {
        $connection->query(\sprintf(<<<'SQL'
            CREATE TABLE IF NOT EXISTS %s (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at BIGINT NOT NULL,
                available_at BIGINT NOT NULL,
                delivered_at BIGINT DEFAULT NULL
            )
            SQL, $table));
        $connection->query(\sprintf('CREATE INDEX IF NOT EXISTS %1$s_available_idx ON %1$s (queue_name, available_at, delivered_at, id)', $table));
    }

    public function insert(SqlTransaction $transaction, string $table, string $body, string $headers, string $queueName, int $delay): mixed
    {
        $now = $this->getNowExpression();

        return $transaction->execute(\sprintf('INSERT INTO %s (body, headers, queue_name, created_at, available_at) VALUES (?, ?, ?, %s, %s + ?) RETURNING id', $table, $now, $now), [$body, $headers, $queueName, $delay])->fetchRow()['id'] ?? null;
    }
}
