<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Mailer\Bridge\MailKite\Transport;

use Psr\EventDispatcher\EventDispatcherInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\Mailer\Envelope;
use Symfony\Component\Mailer\Exception\HttpTransportException;
use Symfony\Component\Mailer\Exception\TransportException;
use Symfony\Component\Mailer\SentMessage;
use Symfony\Component\Mailer\Transport\AbstractApiTransport;
use Symfony\Component\Mime\Email;
use Symfony\Contracts\HttpClient\Exception\DecodingExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Contracts\HttpClient\ResponseInterface;

/**
 * @author Gabe (MailKite) <bucabay@gmail.com>
 */
final class MailKiteApiTransport extends AbstractApiTransport
{
    private const HOST = 'api.mailkite.dev';

    /**
     * Headers carried by the send payload itself, or generated by the receiving
     * MTA. Everything else is passed through the API's `headers` map.
     */
    private const PAYLOAD_HEADERS = [
        'from', 'to', 'cc', 'bcc', 'subject', 'reply-to', 'in-reply-to',
        'content-type', 'content-transfer-encoding', 'mime-version',
        'dkim-signature', 'received', 'message-id', 'date', 'sender', 'return-path',
    ];

    public function __construct(
        #[\SensitiveParameter] private readonly string $key,
        ?HttpClientInterface $client = null,
        ?EventDispatcherInterface $dispatcher = null,
        ?LoggerInterface $logger = null,
    ) {
        parent::__construct($client, $dispatcher, $logger);
    }

    public function __toString(): string
    {
        return \sprintf('mailkite+api://%s', $this->getEndpoint());
    }

    protected function doSendApi(SentMessage $sentMessage, Email $email, Envelope $envelope): ResponseInterface
    {
        $response = $this->client->request('POST', 'https://'.$this->getEndpoint().'/v1/send', [
            'auth_bearer' => $this->key,
            'json' => $this->getPayload($email, $envelope),
        ]);

        try {
            $statusCode = $response->getStatusCode();
            $result = $response->toArray(false);
        } catch (DecodingExceptionInterface) {
            throw new HttpTransportException('Unable to send an email: '.$response->getContent(false).\sprintf(' (code %d).', $response->getStatusCode()), $response);
        } catch (TransportExceptionInterface $e) {
            throw new HttpTransportException('Could not reach the remote MailKite server.', $response, 0, $e);
        }

        if (200 !== $statusCode && 202 !== $statusCode) {
            throw new HttpTransportException('Unable to send an email: '.($result['error'] ?? $response->getContent(false)).\sprintf(' (code %d).', $statusCode), $response);
        }

        if (isset($result['id'])) {
            $sentMessage->setMessageId((string) $result['id']);
        }

        return $response;
    }

    private function getPayload(Email $email, Envelope $envelope): array
    {
        $payload = [
            'from' => $envelope->getSender()->toString(),
            'to' => $this->stringifyAddresses($this->getRecipients($email, $envelope)),
        ];

        if (null !== $email->getSubject()) {
            $payload['subject'] = $email->getSubject();
        }

        if (null !== $text = $email->getTextBody()) {
            $payload['text'] = $text;
        }

        if (null !== $html = $email->getHtmlBody()) {
            $payload['html'] = $html;
        }

        if ($cc = $email->getCc()) {
            $payload['cc'] = $this->stringifyAddresses($cc);
        }

        if ($bcc = $email->getBcc()) {
            $payload['bcc'] = $this->stringifyAddresses($bcc);
        }

        // The API's "replyTo" field holds a single address; more than one is
        // passed through as a raw Reply-To header instead of being truncated.
        if ($replyTo = $email->getReplyTo()) {
            if (1 === \count($replyTo)) {
                $payload['replyTo'] = $replyTo[0]->toString();
            } else {
                $payload['headers']['Reply-To'] = implode(', ', $this->stringifyAddresses($replyTo));
            }
        }

        if ($attachments = $this->getAttachments($email)) {
            $payload['attachments'] = $attachments;
        }

        foreach ($email->getHeaders()->all() as $name => $header) {
            if (\in_array($name, self::PAYLOAD_HEADERS, true)) {
                continue;
            }

            $payload['headers'][$header->getName()] = $header->getBodyAsString();
        }

        if ($inReplyTo = $email->getHeaders()->getHeaderBody('In-Reply-To')) {
            $payload['inReplyTo'] = $inReplyTo;
        }

        return $payload;
    }

    private function getAttachments(Email $email): array
    {
        $attachments = [];
        foreach ($email->getAttachments() as $attachment) {
            $headers = $attachment->getPreparedHeaders();

            // The API has no Content-ID support, so an inline part would be
            // delivered as a plain attachment and its cid: reference would
            // break silently. Fail loudly instead.
            if ('inline' === $headers->getHeaderBody('Content-Disposition')) {
                throw new TransportException('MailKite does not support inline (cid-embedded) attachments; attach the file or host the image at a URL instead.');
            }

            $attachments[] = [
                'filename' => $headers->getHeaderParameter('Content-Disposition', 'filename'),
                'contentType' => $headers->get('Content-Type')->getBody(),
                'content' => base64_encode($attachment->getBody()),
            ];
        }

        return $attachments;
    }

    private function getEndpoint(): string
    {
        return ($this->host ?: self::HOST).($this->port ? ':'.$this->port : '');
    }
}
