<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWeYQspU\Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWeYQspU/Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerWeYQspU.legacy');

    return;
}

if (!\class_exists(Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerWeYQspU\Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer::class, Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer::class, false);
}

return new \ContainerWeYQspU\Symfony_Bridge_PsrHttpMessage_Tests_Fixtures_App_KernelTestDebugContainer([
    'container.build_hash' => 'WeYQspU',
    'container.build_id' => '4fb486a3',
    'container.build_time' => 1696976083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWeYQspU');
