<?php

// This file has been auto-generated by the Symfony Serializer Component.

return [
    'Symfony\Component\Serializer\Tests\Fixtures\Dummy' => [
        [
            'foo' => [[], null, []],
            'bar' => [[], null, []],
            'baz' => [[], null, []],
            'qux' => [[], null, []],
        ],
        null,
    ],
];
