name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          Thanks for your Pull Request! We love contributions.

          However, you should instead open your PR on the main repository:
          https://github.com/symfony/symfony

          This repository is what we call a "subtree split": a read-only subset of that main repository.
          We're looking forward to your PR there!
