name: Lint PhpUnitBridge

on:
  push:
    branches: [ '*.*' ]
    paths:
      - 'src/Symfony/Bridge/PhpUnit/**'
  pull_request:
    paths:
      - 'src/Symfony/Bridge/PhpUnit/**'

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint PhpUnitBridge
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          coverage: "none"
          php-version: "7.1"

      - name: Lint
        run: find ./src/Symfony/Bridge/PhpUnit -name '*.php' | grep -v -e /Tests/ -e ForV7 -e ForV8 -e ForV9 -e ConstraintLogicTrait | parallel -j 4 php -l {}
