name: Lint PhpUnitBridge

on:
  push:
    branches: [ '*.*' ]
    paths:
      - 'src/Symfony/Bridge/PhpUnit/**'
  pull_request:
    paths:
      - 'src/Symfony/Bridge/PhpUnit/**'

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint PhpUnitBridge
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          coverage: "none"
          php-version: "8.1"

      - name: Lint
        run: find ./src/Symfony/Bridge/PhpUnit -name '*.php' | grep -v -e /Tests/ -e /Attribute/ -e /Extension/ -e /Metadata/ -e ForV8 -e ForV9 -e ConstraintLogicTrait -e SymfonyExtension | parallel -j 4 php -l {}
