<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Bridge\Twig\Extension;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\UriSigner;
use Symfony\Component\HttpFoundation\UrlHelper;
use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;

/**
 * Twig extension for the Symfony HttpFoundation component.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
final class HttpFoundationExtension extends AbstractExtension
{
    public function __construct(
        private UrlHelper $urlHelper,
        private ?UriSigner $uriSigner = null,
    ) {
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('absolute_url', $this->generateAbsoluteUrl(...)),
            new TwigFunction('relative_path', $this->generateRelativePath(...)),
        ];
    }

    public function getFilters(): array
    {
        return [
            new TwigFilter('sign_url', $this->signUrl(...)),
        ];
    }

    /**
     * Returns the absolute URL for the given absolute or relative path.
     *
     * This method returns the path unchanged if no request is available.
     *
     * @see Request::getUriForPath()
     */
    public function generateAbsoluteUrl(string $path): string
    {
        return $this->urlHelper->getAbsoluteUrl($path);
    }

    /**
     * Returns a relative path based on the current Request.
     *
     * This method returns the path unchanged if no request is available.
     *
     * @see Request::getRelativeUriForPath()
     */
    public function generateRelativePath(string $path): string
    {
        return $this->urlHelper->getRelativePath($path);
    }

    /**
     * Signs an absolute URL, e.g. one generated by url() or absolute_url().
     *
     * @see UriSigner::sign()
     */
    public function signUrl(string $url, \DateTimeInterface|\DateInterval|int|null $expiration = null): string
    {
        if (null === $this->uriSigner) {
            throw new \LogicException(\sprintf('The "sign_url" filter requires an instance of "%s".', UriSigner::class));
        }

        $parts = parse_url($url);

        if (!isset($parts['scheme'], $parts['host'])) {
            throw new \InvalidArgumentException(\sprintf('The "sign_url" filter requires an absolute URL, "%s" given. Use the "url()" or "absolute_url()" function to generate one.', $url));
        }

        return $this->uriSigner->sign($url, $expiration);
    }
}
